services:
  - type: web
    name: chat-app
    runtime: docker
    dockerfile: Dockerfile.dev
    env: docker
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chat-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health
    port: 3000

  - type: postgres
    name: chat-db
    plan: free
    databaseName: chatdb
    user: chat_user
    ipAllowList: []
